title: JKAN
greeting: Data for Hackdays
description: A lightweight open data portal powered by JKAN.
baseurl: /jkan
logo: https://opendata.ch/files/2014/07/open-knowledge-switzerland-logo-180px.png

# Site theme
jkan_theme: Sandstone

# Authentication
github_client_id: 658541595ae672fb6aaf
gatekeeper_host: https://jkan-opendatach.herokuapp.com/

# Dataset schema
schema: default

# Nav bar
navigation:
  - title: Datasets
    url: /datasets/
  - title: Organizations
    url: /organizations/

# Collections
collections:
  datasets:
    output: true
    permalink: /datasets/:path/
  organizations:
    output: true
    permalink: /organizations/:path/

# Collections (cont'd)
defaults:
  - scope:
      path: ""
      type: datasets
    values:
      layout: dataset
      category: Uncategorized
      organization: N/A
  - scope:
      path: ""
      type: organizations
    values:
      layout: organization

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Google Analytics
google_analytics:
  enabled: false
  code: "UA-XXXXXX-1"

# US Digital Analytics Program - https://analytics.usa.gov
digital_analytics_program:
  enabled: false
  agency: ""
  subagency: ""

# Hypothesis.io - Annotator
hypothesis:
  enabled: true

# Twitter
twittercard:
  enabled: true
  username: "@schoolofdata_ch"

# Open Graph
opengraph:
  enabled: true

# Exclude these files from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .travis.yml
  - node_modules
  - scripts/src
  - package.json
  - webpack.config.js
  - README.md
  - LICENSE
